### ISSUE TITLE
Error: Cannot find module "puppeteer"

### ISSUE THREAD

**Issue by dpdapper** [polastre/united#13]
Successfully installed and ran the script some time ago on my iMac and am now trying to install it on a MacBook Pro, but am receiving the following error (where united-master is the directory where the unzipped repository resides):

XXXMacBookProlocal:united-master David$ node united.js FRA SFO 7/28/2018 8/4/2018
module.js:549
    throw err;
    ^

Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/David/Downloads/united-master/united.js:1:81)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by dpdapper** [comment]
Never mind.  I ran 'npm install" in the wrong directory.  Working now.  Sorry!

**Comment by ctkelley** [comment]
Things were working fine. I updated the OS a couple weeks ago and just tried the app today. I'm getting

node united.js RDU HKG 7/05/18 7/31/18
/Users/ctk/Dropbox/bin_Bartolo/united-master/united.js:10
function getDateString(date, separator = '/') {
                                       ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

Is there an update I've missed?
