### ISSUE TITLE
seems not to work properly anymore

### ISSUE THREAD

**Issue by nyck80** [polastre/united#18]
First I wanna say, this tool is amazing, booked some nice trips because of it, so Thank You! 

- But it appears that the search doesn't work properly anymore. I search within minutes of each other through this tool and the United website for PZ (former R) fare. The tool didn't return a result, but on the website it showed availability. Does it have to do with that the switched from R to PZ fare?

- I also can only search for 10 days at a time without getting an error message:
_(node:1207) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:1207) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
(node:1207) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/Users/nicolasboesch/Downloads/united-master/node_modules/puppeteer/lib/NavigatorWatcher.js:69:21)
(node:1207) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1207) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code._

- Or sometimes I get this message:
_(node:1355) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/Users/nicolasboesch/Downloads/united-master/node_modules/puppeteer/lib/NavigatorWatcher.js:69:21)
(node:1355) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1355) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code._

Any ideas what's going on?

**Comment by handlerda** [comment]
Hi, I am getting the same error. I am in the process of building my own tool and will be sure to share the repo when done.

**Comment by polastre** [comment]
With United discontinuing GPUs and moving to a points system where there's any available seat is always an option (for a price), I don't see a need for a tool like this once GPUs are gone.

**Comment by milesmatthias** [comment]
I'd still like to be able to see availability for confirmed upgrades, rather than waitlist upgrades.

Edit: there is a radio button on the search results to select non-waitlist upgrades.
